- type: loadout
  id: JackSecBoots
  equipment: JackSecBoots

- type: startingGear
  id: JackSecBoots
  equipment:
    shoes: ClothingShoesBootsJackSecFilled

- type: loadout
  id: OuterVestArmorSec
  equipment: OuterVestArmorSec

- type: startingGear
  id: OuterVestArmorSec
  equipment:
    outerClothing: ClothingOuterVestArmorSec
